"""ronnies-chokoloade-factory — Verdens bedste italienske chokolade is

Generated by Keel (Ramboll Developer Platform) from the ``dp-python``
service blueprint. Owned by the Energy department.
"""

from __future__ import annotations

__version__ = "0.1.0"

__all__ = ["__version__"]
