# ronnies-chokoloade-factory — Verdens bedste italienske chokolade is
#
# Terraform infrastructure skeleton, generated by Keel (Ramboll Developer
# Platform) from the `inf-terraform` service blueprint. Owned by the
# Energy department. Grow the stack by adding resources that
# reuse local.name_prefix and local.default_tags.

terraform {
  required_version = ">= 1.7.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }

  # Remote state: configure an azurerm backend per environment before the
  # first real apply (see README "State & backends"). CI validates with
  # `terraform init -backend=false`, so this block may stay commented until
  # the state storage exists.
  #
  # backend "azurerm" {
  #   resource_group_name  = "rg-terraform-state"
  #   storage_account_name = "sttfstate<org>"
  #   container_name       = "tfstate"
  #   key                  = "ronnies-chokoloade-factory.<environment>.tfstate"
  # }
}

provider "azurerm" {
  features {}
}

locals {
  project     = "ronnies-chokoloade-factory"
  name_prefix = "${local.project}-${var.environment}"

  default_tags = {
    project     = local.project
    environment = var.environment
    department  = "energy"
    managed_by  = "terraform"
  }
}

# The stack's root container. Every subsequent resource belongs in (or under)
# this resource group and inherits the naming/tagging conventions above.
resource "azurerm_resource_group" "main" {
  name     = "rg-${local.name_prefix}"
  location = var.location
  tags     = merge(local.default_tags, var.tags)
}
