import { cx } from "./lib/classNames";

/**
 * Root component for ronnies-chokoloade-factory — Verdens bedste italienske chokolade is
 *
 * Generated by Keel (Ramboll Developer Platform) from the `fe-react` service
 * blueprint. Owned by the Energy department. Replace this shell
 * with the real product surface; keep presentational logic in pure `src/lib/`
 * helpers so it stays property-testable (see `src/lib/classNames.ts`).
 */
export function App() {
  return (
    <main className={cx("app", "app--ready")}>
      <h1>ronnies-chokoloade-factory</h1>
      <p>Verdens bedste italienske chokolade is</p>
      <p data-testid="status">green from birth</p>
    </main>
  );
}
